name: Update Google Sheet → JSON

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis

      - name: Decode service account JSON
        run: |
          printf "%s" "${{ secrets.GOOGLE_SA_JSON_BASE64 }}" | base64 --decode > sa.json


      - name: Fetch sheet and write JSON
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_RANGE: ${{ secrets.SHEET_RANGE }}
          GOOGLE_SA_JSON_PATH: sa.json
          OUTPUT_PATH: assets/json/table_data.json
        run: node _scripts/fetch_sheet_private.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/json/table_data.json
          git commit -m "chore: update table_data.json from Google Sheet" || echo "No changes to commit"
          git push
